name: Documentation Issue
description: Report an issue with the documentation
title: "[DOCS] "
labels: ["documentation", "triage"]
assignees: []
body:
  - type: input
    id: page-url
    attributes:
      label: Page URL
      description: Link to the page where the issue is located
      placeholder: https://muhammad-fiaz.github.io/logly.zig/guide/sinks.html
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Type of Issue
      description: What type of documentation issue is this?
      options:
        - "Incorrect information"
        - "Missing information"
        - "Outdated information"
        - "Confusing or unclear content"
        - "Broken links"
        - "Formatting issues"
        - "Code examples don't work"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the documentation issue
      placeholder: What is wrong, missing, or confusing about the documentation?
    validations:
      required: true

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix
      description: If you have a suggestion on how to fix it, please describe it here.
      placeholder: |
        How should this be fixed? Provide:
        - Corrected text
        - Additional content needed
        - Better examples
        - Improved structure
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the documentation issue here.
      placeholder: |
        - Screenshots of the problematic section
        - Links to related documentation
        - Your experience level with Logly
        - How this affects your usage
    validations:
      required: false

  - type: dropdown
    id: contribution-interest
    attributes:
      label: Contribution Interest
      description: Are you interested in helping fix this documentation issue?
      options:
        - "No, I just want to report it"
        - "Yes, I can help fix this"
        - "Maybe, I'd like to contribute but need guidance"
        - "Not sure yet"
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have checked that this issue doesn't already exist
          required: true
        - label: The issue is with the documentation, not the code
          required: true
