name: Help Wanted
description: Ask for help or support with Logly
title: "[HELP] "
labels: ["help wanted", "question"]
assignees: []
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Describe the problem you are facing or the question you have.
      placeholder: What are you trying to accomplish? What issue are you encountering?
    validations:
      required: true

  - type: textarea
    id: code-snippet
    attributes:
      label: Code Snippet
      description: Provide a code snippet that demonstrates the issue or your current implementation.
      placeholder: |
        ```zig
        const std = @import("std");
        const logly = @import("logly");

        pub fn main() !void {
            // Your code here
        }
        ```
      render: zig
    validations:
      required: false

  - type: textarea
    id: attempted-solutions
    attributes:
      label: What Have You Tried?
      description: Describe what you have tried so far to solve the problem.
      placeholder: |
        - Tried different configuration options
        - Looked at documentation/examples
        - Searched for similar issues
        - Other approaches
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What should your code do? How should Logly behave?
    validations:
      required: false

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: What error messages did you get? What unexpected behavior occurred?
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Logly Version
      description: What version of Logly are you using?
      placeholder: e.g., 0.0.2
    validations:
      required: true

  - type: input
    id: zig-version
    attributes:
      label: Zig Version
      description: What Zig version are you using?
      placeholder: e.g., 0.15.0
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: e.g., Windows 11, macOS 14.0, Ubuntu 22.04
    validations:
      required: true

  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: How urgent is this help request?
      options:
        - "Not urgent - just exploring"
        - "Somewhat urgent - blocking progress"
        - "Very urgent - deadline approaching"
        - "Critical - production issue"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about your question or problem here.
      placeholder: |
        - Project context
        - Performance requirements
        - Integration with other systems
        - Links to related code/issues
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have checked the documentation and examples
          required: true
        - label: I have searched for similar questions/issues
          required: true
        - label: This is a support question, not a bug report
          required: true
